import type { AuditReport } from "@/lib/types";

/** Public demo report for /r/sample — no database required. */
export const SAMPLE_REPORT_ID = "sample";

export function getSampleReport(): AuditReport {
  return {
    url: "https://example.com/",
    scannedAt: "2026-07-15T12:00:00.000Z",
    tier: "full",
    scores: { seo: 72, performance: 81, accessibility: 88, security: 76 },
    summary: { critical: 2, warning: 5, info: 4 },
    serpPreview: {
      title: "Example Domain — Sample SEOHub Report",
      description:
        "This is a public sample of an SEOHub full-site audit: scores, crawl coverage, and fix recommendations.",
      url: "example.com/",
    },
    performanceMetrics: {
      lcp: "2.4 s",
      cls: "0.05",
      inp: "120 ms",
      fcp: "1.1 s",
      ttfb: "280 ms",
    },
    checklist: {
      passCount: 42,
      failCount: 6,
      attentionCount: 8,
      hasCount: 42,
      missingCount: 6,
      warningCount: 8,
      summary: "42 pass · 6 fail · 8 need attention",
      items: [
        {
          id: "title",
          label: "Title tag",
          status: "pass",
          category: "seo",
          explanation: "Title is present and a healthy length.",
        },
        {
          id: "meta-desc",
          label: "Meta description",
          status: "attention",
          category: "seo",
          explanation: "Description is a bit short for SERP snippets.",
          fixHint: "Aim for 140–160 characters with a clear CTA.",
        },
        {
          id: "canonical",
          label: "Canonical tag",
          status: "fail",
          category: "technical",
          explanation: "Homepage is missing a self-referencing canonical.",
          fixHint: 'Add <link rel="canonical" href="https://example.com/">',
        },
        {
          id: "https",
          label: "HTTPS",
          status: "pass",
          category: "security",
          explanation: "Site serves over HTTPS.",
        },
      ],
    },
    crawl: {
      enabled: true,
      pagesScanned: 4,
      totalPagesFound: 4,
      pagesDiscovered: 4,
      hitCap: false,
      controls: {
        maxPages: 200,
        includePaths: [],
        excludePaths: [],
      },
      coverage: {
        withCanonical: 2,
        missingCanonical: 2,
        selfCanonical: 2,
        redirected: 1,
        withHreflang: 0,
        orphans: 1,
        maxDepth: 2,
        byDepth: [
          { depth: 0, count: 1 },
          { depth: 1, count: 2 },
          { depth: 2, count: 1 },
        ],
      },
      allPagePaths: ["/", "/about", "/blog", "/blog/hello-world"],
      pages: [
        {
          url: "https://example.com/",
          pathname: "/",
          title: "Example Domain — Sample SEOHub Report",
          description: "Public sample of an SEOHub audit.",
          hasH1: true,
          status: 200,
          canonical: "https://example.com/",
          wordCount: 420,
          h1Count: 1,
          depth: 0,
          inboundLinks: 0,
          redirected: false,
          hreflangCount: 0,
        },
        {
          url: "https://example.com/about",
          pathname: "/about",
          title: "About Example",
          description: "",
          hasH1: true,
          status: 200,
          wordCount: 180,
          h1Count: 1,
          depth: 1,
          inboundLinks: 1,
          redirected: false,
          hreflangCount: 0,
        },
        {
          url: "https://example.com/blog",
          pathname: "/blog",
          title: "Blog",
          description: "Latest posts from Example.",
          hasH1: false,
          status: 200,
          wordCount: 90,
          h1Count: 0,
          depth: 1,
          inboundLinks: 1,
          redirected: false,
          hreflangCount: 0,
        },
        {
          url: "https://example.com/blog/hello-world",
          pathname: "/blog/hello-world",
          title: "Hello World",
          description: "First post.",
          hasH1: true,
          status: 200,
          wordCount: 650,
          h1Count: 1,
          depth: 2,
          inboundLinks: 0,
          redirected: true,
          finalUrl: "https://example.com/blog/hello-world/",
          hreflangCount: 0,
        },
      ],
    },
    siteOverview: {
      domain: { registrar: "Example Registrar", daysUntilExpiry: 400 },
      dns: { hasSpf: true, hasDmarc: false, hasDkim: false, ipv4: ["93.184.216.34"] },
      ssl: { issuer: "Example CA", daysUntilExpiry: 60, protocol: "TLSv1.3" },
      technologies: [
        { name: "Next.js", category: "framework" },
        { name: "Vercel", category: "hosting" },
      ],
      socialProfiles: [],
      externalLinks: { total: 3, uniqueDomains: 2, topDomains: [{ domain: "iana.org", count: 1 }] },
      internalLinks: 6,
      backlinks: { available: false },
    },
    issues: [
      {
        id: "sample-1",
        category: "seo",
        severity: "critical",
        title: "Duplicate page titles found",
        description: "Multiple pages share a weak title pattern in this sample.",
        currentValue: '"Blog" used conceptually on listing pages',
        recommendation: "Give each page a unique, descriptive title tag.",
        pagePath: "/blog",
        pathTemplate: "/blog",
      },
      {
        id: "sample-2",
        category: "seo",
        severity: "critical",
        title: "2 pages missing canonical",
        description: "Canonical tags help Google pick the preferred URL for each page.",
        currentValue: "/about, /blog",
        recommendation: "Add a self-referencing canonical on every indexable page.",
      },
      {
        id: "sample-3",
        category: "seo",
        severity: "warning",
        title: "1 thin content page (< 100 words)",
        description: "Very short pages often rank poorly.",
        currentValue: "/blog",
        recommendation: "Expand useful content or noindex true utility pages.",
        pagePath: "/blog",
        pathTemplate: "/blog",
      },
      {
        id: "sample-4",
        category: "seo",
        severity: "warning",
        title: "Pages missing meta descriptions",
        description: "1 of 4 scanned pages have no meta description.",
        currentValue: "/about",
        recommendation: "Add unique meta descriptions to every indexable page.",
        pagePath: "/about",
        pathTemplate: "/about",
      },
      {
        id: "sample-5",
        category: "seo",
        severity: "warning",
        title: "1 orphan-ish page (no inbound links in crawl)",
        description: "Discovered via sitemap but not linked from other crawled pages.",
        currentValue: "/blog/hello-world",
        recommendation: "Add internal links from related content or navigation.",
        pagePath: "/blog/hello-world",
        pathTemplate: "/blog/:slug",
      },
      {
        id: "sample-6",
        category: "links",
        severity: "warning",
        title: "1 crawled URL redirects",
        description: "Prefer linking directly to the final destination.",
        currentValue: "/blog/hello-world → /blog/hello-world/",
        recommendation: "Update internal links and sitemap entries to the final URL.",
      },
      {
        id: "sample-7",
        category: "seo",
        severity: "info",
        title: "No hreflang tags found in crawl",
        description: "Fine for single-locale sites; add only for true language variants.",
        recommendation: "Skip hreflang unless you serve multiple languages/regions.",
      },
      {
        id: "sample-8",
        category: "security",
        severity: "info",
        title: "Missing Content-Security-Policy header",
        description: "CSP reduces XSS risk when tuned carefully.",
        recommendation: "Add a CSP in report-only mode first, then enforce.",
      },
      {
        id: "sample-9",
        category: "accessibility",
        severity: "info",
        title: "Images missing alt text",
        description: "Sample flag for the demo report.",
        recommendation: "Add descriptive alt text on informative images.",
      },
      {
        id: "sample-10",
        category: "performance",
        severity: "info",
        title: "Consider compressing large images",
        description: "Demo performance tip.",
        recommendation: "Serve modern formats (WebP/AVIF) with sized widths.",
      },
      {
        id: "sample-11",
        category: "seo",
        severity: "warning",
        title: "Pages missing H1 headings",
        description: "1 scanned page has no H1 heading.",
        currentValue: "/blog",
        recommendation: "Add a unique H1 to each page.",
        pagePath: "/blog",
        pathTemplate: "/blog",
      },
    ],
  };
}
